name: 功能建议
description: 为新功能提出建议
title: "[Feature] "
labels: ["待处理"]
assignees:
  - mywwzh
body:
  - type: markdown
    attributes:
      value: |
        感谢您为 OICPP 提出功能建议！
  
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请详细描述你想添加的功能具体是怎样的
      placeholder: 详细描述你想要的功能...
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: 原因
      description: 详细描述你为什么需要这项功能，这有助于开发者评估它的优先度
      placeholder: 为什么需要这个功能...
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: 附加信息
      description: 在此处添加关于该功能建议的任何其他上下文信息或截图。
      placeholder: 其他信息...
    validations:
      required: false
